# Generated by Django 4.2.4 on 2023-08-24 01:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContenidoSolicitud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resumen', models.CharField(max_length=1500)),
                ('palabras_claves', models.CharField(max_length=256)),
                ('abstract', models.CharField(max_length=256)),
                ('Keywords', models.CharField(max_length=256)),
                ('introduccion', models.CharField(max_length=2000)),
                ('materi_metodos', models.CharField(max_length=2000)),
                ('result_discu', models.CharField(max_length=2000)),
                ('agradecimientos', models.CharField(max_length=1500)),
                ('literact_citada', models.CharField(max_length=2000)),
                ('archivo_adjunto', models.FileField(upload_to='archivos_adjuntos/')),
                ('status', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='EstadoSeguimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=256)),
                ('descripcion', models.CharField(max_length=2000)),
                ('status', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='NivelFormacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=256)),
                ('status', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='PasosSeguimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel', models.CharField(max_length=256)),
                ('nombre', models.CharField(max_length=256)),
                ('dias_programacion', models.CharField(max_length=256)),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'PasosSeguimiento',
            },
        ),
        migrations.CreateModel(
            name='RolAutor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('status', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='UsuarioXFormacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=256)),
                ('fecha_grado', models.CharField(max_length=256)),
                ('resol_conv', models.CharField(max_length=256)),
                ('cert_grado', models.CharField(max_length=256)),
                ('nombre_institucion', models.CharField(max_length=256)),
                ('cert_resol', models.CharField(max_length=256)),
                ('status', models.BooleanField(default=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('nivel_formacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='solicitudes.nivelformacion')),
            ],
        ),
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_articulo', models.CharField(max_length=200)),
                ('autores', models.CharField(max_length=500)),
                ('fecha', models.DateField()),
                ('urls', models.CharField(max_length=256)),
                ('orcid', models.CharField(max_length=256)),
                ('afiliacion', models.CharField(max_length=256)),
                ('status', models.BooleanField(default=True)),
                ('contenidoSolicitud', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='solicitudes.contenidosolicitud')),
            ],
            options={
                'verbose_name': 'Solicitud',
            },
        ),
        migrations.CreateModel(
            name='Seguimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_asignacion', models.DateField()),
                ('fecha_programacion', models.DateField()),
                ('fecha_evaluacion', models.DateField()),
                ('status', models.BooleanField(default=True)),
                ('estado_seguimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estado_seguimiento', to='solicitudes.estadoseguimiento')),
                ('pasos_seguimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pasos_seguimiento', to='solicitudes.pasosseguimiento')),
                ('responsableId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responsable', to=settings.AUTH_USER_MODEL)),
                ('solicitudId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='solicitudes.solicitud')),
            ],
        ),
        migrations.CreateModel(
            name='AutorXSolicitud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True)),
                ('rolautor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='solicitudes.rolautor')),
                ('solicitud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='solicitudes.solicitud')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Anexos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True)),
                ('solicitudId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='solicitudes.solicitud')),
            ],
        ),
    ]
