# Generated by Django 4.2.4 on 2023-08-24 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='seguimiento',
            name='correciones',
            field=models.FileField(default=1, upload_to='archivos_adjuntos/'),
            preserve_default=False,
        ),
    ]
