# Generated by Django 4.2.4 on 2023-09-05 00:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('solicitudes', '0002_seguimiento_correciones'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seguimiento',
            name='correciones',
            field=models.FileField(blank=True, null=True, upload_to='archivos_adjuntos/'),
        ),
        migrations.AlterField(
            model_name='seguimiento',
            name='estado_seguimiento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='estado_seguimiento', to='solicitudes.estadoseguimiento'),
        ),
        migrations.AlterField(
            model_name='seguimiento',
            name='fecha_asignacion',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='seguimiento',
            name='fecha_evaluacion',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='seguimiento',
            name='fecha_programacion',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='seguimiento',
            name='responsableId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='responsable', to=settings.AUTH_USER_MODEL),
        ),
    ]
