# Generated by Django 4.2.4 on 2023-09-10 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0003_alter_seguimiento_correciones_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarioxformacion',
            name='cert_grado',
            field=models.FileField(blank=True, null=True, upload_to='archivos_userformacion/'),
        ),
        migrations.AlterField(
            model_name='usuarioxformacion',
            name='cert_resol',
            field=models.FileField(blank=True, null=True, upload_to='archivos_userformacion/'),
        ),
        migrations.AlterField(
            model_name='usuarioxformacion',
            name='resol_conv',
            field=models.FileField(blank=True, null=True, upload_to='archivos_userformacion/'),
        ),
    ]
