# Generated by Django 4.1.7 on 2023-05-31 03:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('solicitudes', '0003_asignaciones_usuarioxformacion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RolAutor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.DateField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='solicitud',
            name='usuario',
        ),
        migrations.CreateModel(
            name='AutorXSolicitud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rolautor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='solicitudes.rolautor')),
                ('solicitud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='solicitudes.solicitud')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
