# Generated by Django 4.1.7 on 2023-05-31 03:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0004_rolautor_remove_solicitud_usuario_autorxsolicitud'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Asignaciones',
        ),
    ]
