# Generated by Django 4.1.7 on 2023-06-01 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0005_delete_asignaciones'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rolautor',
            name='nombre',
            field=models.CharField(max_length=200),
        ),
    ]
