# Generated by Django 4.2.4 on 2023-09-14 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0005_alter_contenidosolicitud_archivo_adjunto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarioxformacion',
            name='fecha_grado',
            field=models.DateField(),
        ),
    ]
