# Generated by Django 4.1.7 on 2023-06-01 20:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0006_alter_rolautor_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitud',
            name='contenidoSolicitud',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='solicitudes.contenidosolicitud'),
        ),
    ]
