# Generated by Django 4.2.4 on 2023-09-24 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0007_alter_usuarioxformacion_fecha_grado'),
    ]

    operations = [
        migrations.AddField(
            model_name='seguimiento',
            name='cambio_relevante',
            field=models.BooleanField(default=False),
        ),
    ]
