# Generated by Django 4.1.7 on 2023-06-01 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0007_alter_solicitud_contenidosolicitud'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud',
            name='nombre_completo',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='solicitud',
            name='nombre_completo2',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
