# Generated by Django 4.2.4 on 2023-09-24 01:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('solicitudes', '0008_seguimiento_cambio_relevante'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitud',
            name='autores',
        ),
        migrations.AddField(
            model_name='solicitud',
            name='autor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
