# Generated by Django 4.1.7 on 2023-06-26 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0009_solicitud_titulo_articulo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='literatura',
            name='articulo',
        ),
        migrations.RemoveField(
            model_name='literatura',
            name='capitulos',
        ),
        migrations.RemoveField(
            model_name='literatura',
            name='libros',
        ),
        migrations.AlterField(
            model_name='contenidosolicitud',
            name='literact_citada',
            field=models.CharField(max_length=2000),
        ),
        migrations.DeleteModel(
            name='Artículos',
        ),
        migrations.DeleteModel(
            name='Capítuloslibros',
        ),
        migrations.DeleteModel(
            name='Libros',
        ),
        migrations.DeleteModel(
            name='Literatura',
        ),
    ]
