# Generated by Django 4.2.4 on 2023-09-24 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0010_remove_solicitud_autor_solicitud_autores'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AutorXSolicitud',
        ),
        migrations.DeleteModel(
            name='RolAutor',
        ),
    ]
