# Generated by Django 4.2.4 on 2023-09-28 01:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0011_delete_autorxsolicitud_delete_rolautor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuarioxformacion',
            name='cert_resol',
        ),
        migrations.RemoveField(
            model_name='usuarioxformacion',
            name='resol_conv',
        ),
    ]
