# Generated by Django 4.2.4 on 2023-08-15 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0011_seguimiento_responsable'),
    ]

    operations = [
        migrations.AddField(
            model_name='anexos',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='autorxsolicitud',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='contenidosolicitud',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='nivelformacion',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='pasossolicitud',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='rolautor',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='seguimiento',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='usuarioxformacion',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
