# Generated by Django 4.2.4 on 2023-09-29 03:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0013_remove_solicitud_orcid'),
    ]

    operations = [
        migrations.AddField(
            model_name='seguimiento',
            name='formato_evaluacion',
            field=models.FileField(blank=True, null=True, upload_to='archivos/archivos_seguimiento/'),
        ),
        migrations.AlterField(
            model_name='seguimiento',
            name='pasos_seguimiento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pasos_seguimiento', to='solicitudes.pasosseguimiento'),
        ),
    ]
