# Generated by Django 4.2.4 on 2023-09-30 04:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0014_seguimiento_formato_evaluacion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitud',
            name='urls',
        ),
    ]
