# Generated by Django 4.2.4 on 2023-10-02 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0015_remove_solicitud_urls'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pasosseguimiento',
            name='nivel',
            field=models.IntegerField(),
        ),
    ]
