# Generated by Django 4.2.4 on 2023-10-02 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0016_alter_pasosseguimiento_nivel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitud',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
