# Generated by Django 4.2.4 on 2023-08-21 01:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pqrs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='asignacion',
            old_name='funcionarioId',
            new_name='asignadoId',
        ),
    ]
