# Generated by Django 4.2.4 on 2023-09-28 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticacion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='ciudad',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
