# Generated by Django 4.2.4 on 2023-09-28 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticacion', '0002_person_ciudad'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='orcid',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
