# Generated by Django 4.2.4 on 2023-10-02 19:46

import django.contrib.admin.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('authenticacion', '0004_rename_document_type_documenttype_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomLogEntry',
            fields=[
            ],
            options={
                'verbose_name': 'Registro de Inicio de Sesión',
                'verbose_name_plural': 'Registros de Inicio de Sesión',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('admin.logentry',),
            managers=[
                ('objects', django.contrib.admin.models.LogEntryManager()),
            ],
        ),
    ]
